services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hellodb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: my-app
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: